[tool.poetry]
name = "django-init"
version = "0.1.0"
description = "Django playground"
authors = ["pke11y"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
